const LOCALE = "en-US";

const messages = {
  "app.brand": "relay",
  "app.version": "live · v0.1.0",
  "common.loading": "loading…",
  "common.loading.plain": "loading...",
  "common.none": "none",
  "common.now": "now",
  "common.unknown": "unknown",
  "common.noResults": "no results",
  "common.actions": "{count} actions",
  "common.items": "{count} items",
  "common.itemCount": "{count} items in scope",
  "common.repositories": "{count} repositories",
  "common.activeItems": "{count} active items",
  "common.savedSnapshots": "{count} saved {noun}",
  "common.savedSnapshot.noun.one": "snapshot",
  "common.savedSnapshot.noun.many": "snapshots",
  "common.sources": "{count} sources",
  "common.toUndo": "to undo",
  "common.copied": "Copied",
  "common.copy": "copy",
  "common.copyAll": "Copy all",
  "common.clear": "Clear",
  "common.remove": "Remove",
  "common.refresh": "Refresh",
  "common.dismiss": "Dismiss",
  "common.saveCurrentAsView": "Save current as view",
  "common.switchTheme": "Switch to {theme} theme",
  "common.light": "light",
  "common.dark": "dark",
  "common.sunset": "sunset",
  "common.matrix": "matrix",
  "common.ocean": "ocean",
  "common.notebook": "notebook",
  "common.blueprint": "blueprint",
  "common.washi": "washi",
  "common.sketch": "sketch",
  "common.paper": "paper",
  "common.mist": "mist",
  "common.midnight": "midnight",
  "common.solar": "solar",
  "common.nord": "nord",
  "common.sakura": "sakura",
  "common.amber": "amber",
  "common.hcDark": "high contrast (dark)",
  "common.hcLight": "high contrast (light)",
  "common.reopen": "Reopen",
  "common.close": "Close",
  "common.snooze": "Snooze",
  "nav.views": "Views",
  "nav.pinnedViews": "Pinned Views",
  "nav.browse": "Browse",
  "nav.sources": "Sources",
  "nav.today": "Today",
  "nav.open": "Open",
  "nav.openTasks": "Open tasks",
  "nav.snoozed": "Snoozed",
  "nav.done": "Done",
  "nav.repos": "Repos",
  "nav.contexts": "Contexts",
  "nav.insights": "Insights",
  "nav.sessions": "Sessions",
  "nav.agenda": "Agenda",
  "agenda.title": "Agenda",
  "agenda.subtitle": "{days}-day calendar of due_at + scheduled tasks",
  "agenda.window.7d": "7d",
  "agenda.window.14d": "14d",
  "agenda.window.30d": "30d",
  "agenda.overdue": "Overdue",
  "agenda.overdue.hint": "past due, still open",
  "agenda.scheduled": "Scheduled (no date)",
  "agenda.scheduled.hint": "wait_on=scheduled · no due_at set",
  "agenda.empty": "no due dates or scheduled tasks in window",
  "agenda.emptyHint": "set due dates with `relay add --due YYYY-MM-DD`, or wait_on=scheduled to defer",
  "agenda.dayEmpty": "no tasks",
  "agenda.dueLabel": "due {date}",
  "sessions.title": "Sessions",
  "sessions.filter": "filter title or repo…",
  "sessions.empty": "no sessions in lookback window",
  "sessions.noMatch": "no sessions match \"{filter}\"",
  "sessions.detail.openedFrom": "opened from {cwd}",
  "sessions.detail.noBody": "(no body)",
  "sessions.detail.noTodos": "no todos in this session",
  "sessions.detail.notFound": "session not found",
  "sessions.detail.backToList": "← back to sessions",
  "source.codeTasks": "code tasks",
  "source.githubIssue": "GitHub issue",
  "source.githubPr": "GitHub PR",
  "source.ghNotification": "GitHub notification",
  "source.ghRunFailure": "CI failure",
  "source.ghProjectCard": "GitHub Project card",
  "source.gitInterrupted": "git interrupted",
  "source.gitStash": "git stash",
  "source.orphanBranch": "orphan branch",
  "source.claudeSession": "Claude session",
  "source.codexSession": "Codex session",
  "source.antigravitySession": "Antigravity session",
  "source.cursorSession": "Cursor session",
  "source.agents": ".agents",
  "source.manual": "manual",
  "today.hero.title": "Today",
  "today.hero.empty": "nothing for today",
  "today.stat.ageMedian": "age median",
  "today.stat.oldestTask": "oldest task",
  "today.stat.openHint": "active + open",
  "today.stat.contextsHint": "saved snapshots",
  "today.queue.title": "Today's Queue",
  "today.queue.seeAllOpen": "see all open",
  "today.waitOn.self.title": "Waiting on me",
  "today.waitOn.self.hint": "things I drive next",
  "today.waitOn.self.empty": "nothing waiting on me today",
  "today.waitOn.others.title": "Waiting on others",
  "today.waitOn.others.hint": "review / external / scheduled",
  "today.sourceMix": "Source Mix",
  "today.empty.reviewOldest": "Review 5 oldest open →",
  "today.empty.checkYesterday": "Check yesterday's session →",
  "today.empty.staleRepos": "Repos with no activity 14d →",
  "today.empty.recoveryLinks": "Today recovery links",
  "today.focus.banner": "Focus mode",
  "today.focus.hint": "Other Today items, Standup, and the bento grid are hidden while focus is on.",
  "today.focus.exit": "Exit focus",
  "today.focus.runCli": "Copy run command",
  "today.focus.taskLabel": "Focused task",
  "today.focus.missing": "Focus pointed at a missing task — clearing.",
  "standup.title": "Standup",
  "standup.window.24h": "last 24h",
  "standup.window.7d": "last 7d",
  "standup.switchTo24h": "24h",
  "standup.switchTo7d": "7d",
  "standup.yesterday": "Yesterday",
  "standup.yesterday.hint": "closed + successful runs",
  "standup.yesterday.empty": "no closed work in window",
  "standup.today": "Today",
  "standup.today.hint": "waiting on me",
  "standup.today.empty": "nothing self-driven",
  "standup.blockers": "Blockers",
  "standup.blockers.hint": "reviewer / external",
  "standup.blockers.empty": "no blockers",
  "standup.via": "via {agent}",
  "onboarding.title": "Welcome to relay",
  "onboarding.subtitle": "Pick one of the three paths below to get your first tasks in.",
  "onboarding.sync.title": "1. Sync from your existing sources",
  "onboarding.sync.desc": "Pull tasks from configured adapters — code TODOs, GitHub issues / PRs, Claude session todos, .agents/ notes.",
  "onboarding.track.title": "2. Track local repos",
  "onboarding.track.desc": "Add directories to scan.roots so relay resolves repo names to paths.",
  "onboarding.add.title": "3. Add a manual task",
  "onboarding.add.desc": "Type a title and pick a repo + agent — useful when nothing on disk represents the work yet.",
  "onboarding.trackRepos": "Track repos",
  "onboarding.addTask": "Add task",
  "tasks.title.default": "Tasks",
  "tasks.title.open": "Open Tasks",
  "tasks.title.active": "Active",
  "tasks.savePrompt": "Save current as view",
  "tasks.filterHint": "Press",
  "tasks.filterSuffix": "to filter",
  "tasks.empty": "nothing here.",
  "task.select": "select a task →",
  "task.source": "Source",
  "task.age": "Age",
  "task.context": "Context",
  "task.lastTouched": "last touched {age} ago",
  "task.previousContext": "previous context",
  "task.dirtyFiles": "+{count} dirty files",
  "task.repo": "repo",
  "task.assignee": "assignee",
  "task.priority": "priority",
  "task.updated": "updated",
  "task.due": "due",
  "task.session": "session",
  "task.openSession": "Open original session",
  "sessions.detail.tasksHeading": "Tasks · {count}",
  "sessions.detail.noTasks": "No tasks created from this session",
  "task.files": "files",
  "task.scopeToRepo": "scope to {repo}",
  "task.createdAt": "created {date}",
  "task.snoozed": "snoozed",
  "task.snoozedUntil": "snoozed until {date}",
  "command.newTask": "New task…",
  "command.newTaskHint": "create manual task",
  "command.runSync": "Run sync",
  "command.runSyncHint": "POST /api/sync",
  "command.menu": "Command menu",
  "command.placeholder": "Jump to view, run an action, or search tasks…",
  "command.footer": "type to filter · ↑↓ navigate · ↵ select",
  "command.toggle": "toggle",
  "command.view": "View: {name}",
  "cheatsheet.title": "Keymap",
  "cheatsheet.dialog": "Keymap cheatsheet",
  "cheatsheet.subtitle": "Fast paths for the local task hub.",
  "cheatsheet.navigate": "Navigate",
  "cheatsheet.moveSelect": "Move & Select",
  "cheatsheet.action": "Action",
  "cheatsheet.nextTask": "Next task",
  "cheatsheet.previousTask": "Previous task",
  "cheatsheet.openSelected": "Open selected",
  "cheatsheet.focusFilter": "Focus filter",
  "cheatsheet.clearOrClose": "Clear or close",
  "cheatsheet.newTask": "New task",
  "cheatsheet.footer": "Press ? anytime",
  "heatmap.empty": "no heatmap data",
  "heatmap.aria": "Repository velocity and stale heatmap",
  "page.insights.title": "Insights",
  "page.insights.subtitle": "Workflow health · {repos} active repositories",
  "page.insights.w01.label": "Weekly Flow Ratio",
  "page.insights.w01.hint": "8 week sparkline · closed÷opened",
  "page.insights.w01.empty": "Awaiting data",
  "page.insights.w02.label": "Repos touched 7d",
  "page.insights.w02.hint": "of {total} tracked",
  "page.insights.w03.label": "Close / Open ratio",
  "page.insights.w03.hint": "{closed} closed · {opened} opened (7d)",
  "page.insights.w04.label": "Stale ratio (14d)",
  "page.insights.w04.hint": "{stale} of {total} open",
  "page.insights.w05.label": "Wait median age",
  "page.insights.w05.hint": "{n} samples",
  "page.insights.w05.unit": "d",
  "page.insights.w06.title": "Velocity & stale heatmap",
  "page.insights.w07.title": "Top stalled repos",
  "page.insights.w07.empty": "no stalled repos",
  "page.insights.w07.item": "{open} open · {days}d stale",
  "page.insights.w08.title": "Newly active repos",
  "page.insights.w08.empty": "no new activity",
  "page.insights.w08.item": "{n} new tasks",
  "page.insights.w09.title": "Opened vs closed · 30d",
  "page.insights.w09.empty": "no flow data",
  "page.insights.w10.title": "Wait-on mix",
  "page.insights.w10.empty": "no waiting tasks",
  "page.insights.w11.title": "Reviewer-blocked PRs",
  "page.insights.w11.empty": "no reviewer-blocked PRs",
  "page.insights.w15.title": "Task age histogram",
  "page.insights.w15.empty": "no open tasks",
  "page.insights.w15.aria": "Open task age distribution by bucket",
  "page.insights.section4Title": "Source & Agent Mix",
  "page.insights.section4bTitle": "Sync reliability",
  "page.insights.section6Title": "Orphan open tasks",
  "page.insights.w12.title": "Source inflow · 7d vs prev",
  "page.insights.w12.empty": "no inflow data",
  "page.insights.w12.legend.curr": "current",
  "page.insights.w12.legend.prev": "previous",
  "page.insights.w12.other": "Other ({n})",
  "page.insights.w13.title": "Runs by agent · 30d",
  "page.insights.w13.empty": "no run history",
  "page.insights.w13.failed": "{n} failed",
  "page.insights.w13.aria": "Runs per agent with failed overlay",
  "page.insights.w14.title": "Sync reliability · 7d",
  "page.insights.w14.empty": "No sync history yet",
  "page.insights.w14.aria": "Adapter sync status grid",
  "page.insights.w14.legend.ok": "ok",
  "page.insights.w14.legend.partial": "partial",
  "page.insights.w14.legend.error": "error",
  "page.insights.w14.legend.none": "none",
  "page.insights.w16.title": "Context freshness",
  "page.insights.w16.empty": "no context snapshots yet",
  "page.insights.w16.never": "never",
  "page.insights.w16.unit": "d",
  "page.insights.w16.openHint": "{n} open",
  "page.insights.w17.empty": "No orphans 🌱",
  "page.insights.w17.subtitle": "{age}d+ untouched · top {limit}",
  "page.insights.w17.col.id": "#",
  "page.insights.w17.col.repo": "repo",
  "page.insights.w17.col.title": "title",
  "page.insights.w17.col.priority": "pri",
  "page.insights.w17.col.age": "age",
  "page.insights.w17.ageDays": "{n}d",
  "page.insights.w18.title": "Weekly flow ratio · 12w",
  "page.insights.w18.expand": "Show 12w trend",
  "page.insights.w18.collapse": "Hide 12w trend",
  "page.insights.w18.empty": "Awaiting data",
  "page.insights.w18.aria": "Weekly flow ratio 12 week line chart",
  "page.insights.wait.self": "self",
  "page.insights.wait.reviewer": "reviewer",
  "page.insights.wait.external": "external",
  "page.insights.wait.scheduled": "scheduled",
  "page.insights.error.hint": "Could not load insight data.",
  "review.closedLastWeek": "Closed last week",
  "review.stale7d": "Stale >= 7d",
  "review.newThisWeek": "New this week",
  "review.recentlyUnsnoozed": "Recently unsnoozed",
  "repos.title": "Repos",
  "repos.filter": "filter repos…",
  "repos.empty": "no repos — try `relay sync`",
  "repos.noMatch": "no repos match '{filter}'",
  "repos.stat.open": "open",
  "repos.stat.active": "active",
  "repos.stat.snooze": "snooze",
  "repos.activity14d": "14 day activity: {counts}",
  "contexts.title": "Contexts",
  "contexts.filter": "filter contexts…",
  "contexts.subtitle": "{count} saved {noun} · auto-captured via Stop hook",
  "contexts.empty": "no contexts yet — run `relay hook install` then use Claude Code",
  "contexts.noMatch": "no contexts match '{filter}'",
  "contexts.scopeTasks": "scope tasks to {repo}",
  "contexts.resumableTitle": "resumable Claude Code session",
  "contexts.resumable": "resumable",
  "contexts.dirty": "+{count} dirty",
  "queue.title": "Run Queue",
  "queue.tray": "Run queue tray",
  "queue.empty": "Queue is empty.",
  "queue.removeTask": "Remove task {id} from queue",
  "toast.notifications": "Notifications",
  "toast.closed": "Closed",
  "toast.snoozed": "Snoozed",
  "toast.snoozedUntilWeekday": "Snoozed {days}d → {weekday}",
  "toast.undo": "Undo",
  "toast.undoAction": "Undo {count} {action} {noun}",
  "toast.action.one": "action",
  "toast.action.many": "actions",
  "toast.dismiss": "Dismiss toast",
  "toast.viewSnoozed": "View snoozed →",
  "page.tasks.emptyTitle": "No match for the current filter",
  "page.tasks.emptyHint": "No match for the current filter. Press / to refine.",
  "page.agenda.emptyTitle": "Nothing scheduled in this window",
  "page.agenda.emptyHint": "Nothing scheduled in this window. Set due dates with `relay add --due YYYY-MM-DD`, or widen the range to 14d / 30d.",
  "page.sessions.emptyTitle": "No AI sessions in this window",
  "page.sessions.emptyHint": "No AI sessions in this window. Try widening lookback to 90d.",
  "page.repos.emptyTitle": "No tracked repos yet",
  "page.repos.emptyHint": "No tracked repos yet. Click + Track repos above or run `relay sync`.",
  "page.contexts.emptyTitle": "No context snapshots yet",
  "page.contexts.emptyHint": "No context snapshots yet. Run `relay sync` to capture sessions.",
} as const;

export type CopyKey = keyof typeof messages;

export function c(key: CopyKey, vars?: Record<string, string | number>): string {
  const tmpl: string = messages[key];
  if (!vars) return tmpl;

  return Object.entries(vars).reduce(
    (value, [name, replacement]) => value.replaceAll(`{${name}}`, String(replacement)),
    tmpl,
  );
}

const numberFormatter = new Intl.NumberFormat(LOCALE);
const shortDateFormatter = new Intl.DateTimeFormat(LOCALE, { month: "short", day: "numeric" });
const weekdayFormatter = new Intl.DateTimeFormat(LOCALE, { weekday: "short" });
const monthDayTimeFormatter = new Intl.DateTimeFormat(LOCALE, {
  month: "short",
  day: "numeric",
  hour: "2-digit",
  minute: "2-digit",
});
const utcNumericDateFormatter = new Intl.DateTimeFormat(LOCALE, {
  month: "numeric",
  day: "numeric",
  timeZone: "UTC",
});
const utcLongDateFormatter = new Intl.DateTimeFormat(LOCALE, {
  month: "short",
  day: "numeric",
  year: "numeric",
  timeZone: "UTC",
});

export function formatNumber(value: number): string {
  return numberFormatter.format(value);
}

export function formatShortDate(date: Date): string {
  return shortDateFormatter.format(date);
}

export function formatWeekday(date: Date): string {
  return weekdayFormatter.format(date);
}

export function formatMonthDayTime(date: Date): string {
  return monthDayTimeFormatter.format(date);
}

export function formatUtcNumericDate(date: Date): string {
  return utcNumericDateFormatter.format(date);
}

export function formatUtcLongDate(date: Date): string {
  return utcLongDateFormatter.format(date);
}
